<?php

/**
 * BaseuserPlaylist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $playit_id
 * @property sfGuardUser $sfGuardUser
 * @property playIt $playIt
 * 
 * @method integer      getUserId()      Returns the current record's "user_id" value
 * @method integer      getPlayitId()    Returns the current record's "playit_id" value
 * @method sfGuardUser  getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method playIt       getPlayIt()      Returns the current record's "playIt" value
 * @method userPlaylist setUserId()      Sets the current record's "user_id" value
 * @method userPlaylist setPlayitId()    Sets the current record's "playit_id" value
 * @method userPlaylist setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method userPlaylist setPlayIt()      Sets the current record's "playIt" value
 * 
 * @package    islam
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseuserPlaylist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_playlist');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('playit_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('playIt', array(
             'local' => 'playit_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}