<?php

/**
 * Basecategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $category_name
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $reports
 * @property Doctrine_Collection $articles
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getUserId()        Returns the current record's "user_id" value
 * @method string              getCategoryName()  Returns the current record's "category_name" value
 * @method sfGuardUser         getSfGuardUser()   Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getReports()       Returns the current record's "reports" collection
 * @method Doctrine_Collection getArticles()      Returns the current record's "articles" collection
 * @method category            setId()            Sets the current record's "id" value
 * @method category            setUserId()        Sets the current record's "user_id" value
 * @method category            setCategoryName()  Sets the current record's "category_name" value
 * @method category            setSfGuardUser()   Sets the current record's "sfGuardUser" value
 * @method category            setReports()       Sets the current record's "reports" collection
 * @method category            setArticles()      Sets the current record's "articles" collection
 * 
 * @package    addakirine
 * @subpackage model
 * @author     Abderrahman JIHAL
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('category_name', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));


        $this->index('fk_category_user1', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('report as reports', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('article as articles', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}