<?php

/**
 * BaseplayIt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $play_list_id
 * @property string $name
 * @property clob $description
 * @property user $user
 * @property playList $playList
 * @property Doctrine_Collection $reports
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getUserId()       Returns the current record's "user_id" value
 * @method integer             getPlayListId()   Returns the current record's "play_list_id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method clob                getDescription()  Returns the current record's "description" value
 * @method user                getUser()         Returns the current record's "user" value
 * @method playList            getPlayList()     Returns the current record's "playList" value
 * @method Doctrine_Collection getReports()      Returns the current record's "reports" collection
 * @method playIt              setId()           Sets the current record's "id" value
 * @method playIt              setUserId()       Sets the current record's "user_id" value
 * @method playIt              setPlayListId()   Sets the current record's "play_list_id" value
 * @method playIt              setName()         Sets the current record's "name" value
 * @method playIt              setDescription()  Sets the current record's "description" value
 * @method playIt              setUser()         Sets the current record's "user" value
 * @method playIt              setPlayList()     Sets the current record's "playList" value
 * @method playIt              setReports()      Sets the current record's "reports" collection
 * 
 * @package    islam
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseplayIt extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('play_it');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('play_list_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('description', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));


        $this->index('fk_play_it_user1', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('user', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('playList', array(
             'local' => 'play_list_id',
             'foreign' => 'id'));

        $this->hasMany('report as reports', array(
             'local' => 'id',
             'foreign' => 'play_it_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}