<?php

/**
 * Basearticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $category_id
 * @property string $title
 * @property clob $article_text
 * @property user $user
 * @property category $category
 * @property Doctrine_Collection $reports
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getUserId()       Returns the current record's "user_id" value
 * @method integer             getCategoryId()   Returns the current record's "category_id" value
 * @method string              getTitle()        Returns the current record's "title" value
 * @method clob                getArticleText()  Returns the current record's "article_text" value
 * @method user                getUser()         Returns the current record's "user" value
 * @method category            getCategory()     Returns the current record's "category" value
 * @method Doctrine_Collection getReports()      Returns the current record's "reports" collection
 * @method article             setId()           Sets the current record's "id" value
 * @method article             setUserId()       Sets the current record's "user_id" value
 * @method article             setCategoryId()   Sets the current record's "category_id" value
 * @method article             setTitle()        Sets the current record's "title" value
 * @method article             setArticleText()  Sets the current record's "article_text" value
 * @method article             setUser()         Sets the current record's "user" value
 * @method article             setCategory()     Sets the current record's "category" value
 * @method article             setReports()      Sets the current record's "reports" collection
 * 
 * @package    islam
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basearticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('article_text', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));


        $this->index('fk_article_user1', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->index('fk_article_category1', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('user', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasMany('report as reports', array(
             'local' => 'id',
             'foreign' => 'article_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}