<?php

/**
 * Basetrack
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $play_list_id
 * @property string $name
 * @property string $url
 * @property sfGuardUser $sfGuardUser
 * @property playList $playList
 * @property Doctrine_Collection $tracks
 * @property Doctrine_Collection $reports
 * @property Doctrine_Collection $userPlaylists
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getUserId()        Returns the current record's "user_id" value
 * @method integer             getPlayListId()    Returns the current record's "play_list_id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getUrl()           Returns the current record's "url" value
 * @method sfGuardUser         getSfGuardUser()   Returns the current record's "sfGuardUser" value
 * @method playList            getPlayList()      Returns the current record's "playList" value
 * @method Doctrine_Collection getTracks()        Returns the current record's "tracks" collection
 * @method Doctrine_Collection getReports()       Returns the current record's "reports" collection
 * @method Doctrine_Collection getUserPlaylists() Returns the current record's "userPlaylists" collection
 * @method track               setId()            Sets the current record's "id" value
 * @method track               setUserId()        Sets the current record's "user_id" value
 * @method track               setPlayListId()    Sets the current record's "play_list_id" value
 * @method track               setName()          Sets the current record's "name" value
 * @method track               setUrl()           Sets the current record's "url" value
 * @method track               setSfGuardUser()   Sets the current record's "sfGuardUser" value
 * @method track               setPlayList()      Sets the current record's "playList" value
 * @method track               setTracks()        Sets the current record's "tracks" collection
 * @method track               setReports()       Sets the current record's "reports" collection
 * @method track               setUserPlaylists() Sets the current record's "userPlaylists" collection
 * 
 * @package    islam
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basetrack extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('track');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('play_list_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('fk_Track_user1', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('playList', array(
             'local' => 'play_list_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('sfGuardUser as tracks', array(
             'refClass' => 'userPlaylist',
             'local' => 'track_id',
             'foreign' => 'id'));

        $this->hasMany('report as reports', array(
             'local' => 'id',
             'foreign' => 'Track_id'));

        $this->hasMany('userPlaylist as userPlaylists', array(
             'local' => 'id',
             'foreign' => 'track_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}