<?php

/**
 * articleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class articleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object articleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('article');
    }
}