<?php

/**
 * playListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class playListTable extends Doctrine_Table
{

    const PLAYLIST_QURAN = 'quran',
    PLAYLIST_ANACHID = 'anachid';

    /**
     * Returns an instance of this class.
     *
     * @return object playListTable
     */
    public static function getInstance()
    {
	return Doctrine_Core::getTable('playList');
    }

    public function getPlaylists($id)
    {
	$q = Doctrine_Query::create()
		->from('playList pl')
		->leftJoin('pl.playOwner po')
//		->addWhere('id = ? ', $id)
		->execute();
	
	return $q;
    }

}