<?php

/**
 * playItTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class playItTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object playItTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('playIt');
    }
    
}