<?php

/**
 * reportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class reportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object reportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('report');
    }
}