<?php

/**
 * userPlaylistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class userPlaylistTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object userPlaylistTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('userPlaylist');
  }

  /**
   *  si l'utilisateur est connecté afficher la playlist de l user sinon
   *  afficher une liste au hasard
   * 
   * @todo verifier si l user est dans la page d un playlist, alor afficher les mp3 de ce dernier
   * @param integer $userId
   * @return type 
   */
  public function loadUserPlaylist($userId, $playOwnerId)
  {
    $q = Doctrine_Query::create()
            ->from('userPlayList upl')
            ->leftJoin('upl.sfGuardUser u')
            ->leftJoin('upl.track pi')
            ->leftJoin('pi.playList pl')
            ->leftJoin('pl.playOwner po');
    
    //$q = ($playOwnerId !== null)? $q->addWhere('po.id = ?', $playOwnerId): '';
    $q = ($userId === null) ? $q->limit(10) : $q->addWhere('upl.user_id = ?', $userId);

    return $q->execute();
  }

}