<?php

/**
 * userPlaylistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class userPlaylistTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object userPlaylistTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('userPlaylist');
  }

  public function loadUserPlaylist($userId) {
    $q = Doctrine_Query::create()
            ->from('userPlayList upl')
            ->addWhere('upl.user_id = ?', $userId)
            ->leftJoin('upl.sfGuardUser u')
            ->leftJoin('upl.track pi')
            ->leftJoin('pi.playList pl')
            ->leftJoin('pl.playOwner po')
            ->execute();

    return $q;
  }

}