# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App
dev:
  sfCombinePlugin:
    enabled:        false
# default values
all:
  imagesUpload:
    rightMenuPub: /uploads/pub/
    
  user:
    default_group: simple_user

#sfForkedDoctrinePlugin
  sfApplyPlugin:
    from:
      email: "contact@addakirine.com"
      fullname: "Addakirine Staff"
  sfForkedApply:  
    mail_editable: false
    routes:
      apply: /user/register
      reset: /user/password-reset
      resetRequest: /user/reset-request
      resetCancel: /user/reset-cancel
      validate: /user/confirm/:validate
      settings: /user/settings
    
sfCombinePlugin:
    enabled:        false     # enabling the plugin will combine script and css files into a single file
    asset_version:  1        # key to the asset version (see below)
    client_cache_max_age: 10 # enable the browser to keep a copy of the files for x days (false to disable)
    gzip:           true     # allow PHP gzipping of the combined JavaScript and CSS files to reduce bandwidth usage (false to disable)
    js:
      combine_skip:          # these files will not be combined (necessary when js code is based on js file name)
        - /js/tiny_mce/tiny_mce.js
      minify:       true     # minification removes whitespaces and comments
      minify_skip:           # these files will not be minified (useful when code is already minified)
        - jquery.min.js
      pack:         false    # packing reduces the filesize by using a JavaScript compression (warning: see below)
      pack_skip:             # these files will not be packed (necessary when a third party js lib doesn't support packing)
    css:
      minify:       true     # only minification is available for css