# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - FO/reset_rtl.css
    - FO/960.css
#    - FO/niceforms-default.css
    - FO/form-structure.css
    - FO/form-style.css
    - FO/zebra_dialog.css
    - FO/player.css
    - FO/init_style.css
#    - FO/tipTip.css

  javascripts:    
   - libs/jquery.jplayer.min.js
#   - libs/niceforms.js
#   - libs/jquery.tipTip.minified.js
   - libs/zebra_dialog.js
   - mylibs/fo/qu.common.js
   - mylibs/fo/qu.playlist.js
   - plugins.js
   - script.js

  has_layout:     true
  layout:         layout
  
all:
  components:
    right_menu: [home, rightMenu]