# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [FO/reset_rtl.css, FO/960.css, FO/style.css, FO/style2.css]

  javascripts:    [jquery.js]

  has_layout:     true
  layout:         layout
