generator:
  class: sfDoctrineGenerator
  param:
    model_class:           track
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          track
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:   
        display: [login, playListTitle, name, url]
      filter:  
        class: false
      form:    
        class: boTrackForm
      edit:    ~
      new:     ~
